---
- name: Delete existing {{ name }} secret
  shell: "kubectl delete secret {{ name }} --namespace={{ ns }}"
  ignore_errors: yes

- name: Create {{ name }} secret (TLS)
  shell: "kubectl create secret tls {{ name }} --key {{ certs }}/{{ tls_filename }}.key --cert {{ certs }}/{{ tls_filename }}.crt --namespace={{ ns }}"
  when: secret_type == 'tls'

- name: Create {{ name }} secret (Docker)
  shell: "kubectl create secret docker-registry {{ name }} --docker-server={{ docker.registry }} --docker-username={{ docker.user }} --docker-password={{ docker.password }} --docker-email={{ docker.email }} --namespace={{ ns }}"
  when: secret_type == 'docker'

- name: Create {{ name }} secret (Generic)
  shell: "kubectl create secret generic {{ name }} {{ files | unique | format_list('--from-file={0}') | join(' ')}} --namespace={{ ns }}" 
  when: secret_type == 'generic'


